import { library } from '@fortawesome/fontawesome-svg-core'
import { faTimesCircle } from '@fortawesome/free-regular-svg-icons'
import { 
    faClock, 
    faArrowLeft, 
    faArrowRight,
    faBars,
    faEnvelope,
    faPhone,
    faDatabase,
    faPizzaSlice,
    faSoap,
    faBirthdayCake,
    faWineGlassAlt,
    faBacon,
    faBreadSlice,
    faSignOutAlt,
    faCartArrowDown,
    faShoppingCart,
    faTrashAlt,
} from '@fortawesome/free-solid-svg-icons'

import { 
    faGithub,
    faLinkedin,
    faFacebookSquare,
    faPhp,
    faLaravel,
    faJsSquare,
    faVuejs,
    faBootstrap,
    faCss3Alt,
    faSass,
    faHtml5,
    faGitAlt,
    faWindows,
    faNpm,
    faTripadvisor,
    faTwitter,
    faYoutube,
    faInstagram,
} from '@fortawesome/free-brands-svg-icons'

library.add(
    faGithub,
    faLinkedin,
    faClock,
    faArrowLeft,
    faArrowRight,
    faFacebookSquare,
    faBars,
    faTimesCircle,
    faEnvelope,
    faPhone,
    faPhp,
    faLaravel,
    faDatabase,
    faJsSquare,
    faVuejs,
    faBootstrap,
    faCss3Alt,
    faSass,
    faHtml5,
    faGitAlt,
    faWindows,
    faNpm,
    faPizzaSlice,
    faSoap,
    faBirthdayCake,
    faWineGlassAlt,
    faBacon,
    faBreadSlice,
    faSignOutAlt,
    faCartArrowDown,
    faShoppingCart,
    faTrashAlt,
    faTripadvisor,
    faTwitter,
    faYoutube,
    faInstagram,
)